version: '3'
services:
  twinp2g:
    container_name: twinp2g-container
    restart: always
    image: twinp2g-image3
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - 8501
    ports:
      - 8501:8501
    environment:
      - ENV_PATH="/root/miniconda3/bin:${PATH}"
    volumes:
      - results:/app/results
    networks:
      - ds_viz_network

networks: 
  ds_viz_network:
    external: true

volumes:
  results:  